import "@/ui/global.css";

import type { Metadata } from "next";

import { ColorModeScript, Provider } from "@/ui/chakra";
import { config } from "@/ui/chakra-config";

export const metadata: Metadata = {
  title: "AA Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Provider>{children}</Provider>
        <ColorModeScript initialColorMode={config.initialColorMode} />
      </body>
    </html>
  );
}
