import "@/ui/global.css";

import type { Metadata } from "next";

import { demo } from "@/config";
import { Provider } from "@/ui/chakra";
import { ColorModeScript, ThemeConfig } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "AA Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config: ThemeConfig = {
    initialColorMode: "dark",
    useSystemColorMode: false,
  };

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Provider config={config}>
          {demo.enabled && <demo.DemoBanner />}
          {children}
        </Provider>
        <ColorModeScript initialColorMode={config.initialColorMode} />
      </body>
    </html>
  );
}
